#!/bin/sh
jupyter contrib nbextension install --user
jupyter nbextension enable codefolding/main
python -m cite2c.install
result=$(python <<EOF
from notebook.services.config.manager import ConfigManager
cm = ConfigManager()
cm.update('cite2c', {'zotero':{"user_id": "5043554","username": "econ-ark","access_token": "XZpH9NsoAZmDMmjLKiy8xMXX"}})
EOF
      )
# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('TkAgg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"
	
test -e test.png && rm test.png

